theme: jekyll-theme-cayman
title: Kailee Madden
description: Here you can find the variety and depth of Kailee's academic and personal interests, such as a thesis combining history, philosophy, mathematics, and physics, or a Twitter Bot that posts the daily surf report for the San Diego area.
